name: 'Tailcall Deploy Action'
description: 'Deploy Tailcall application with AWS and Fly.io configurations'
inputs:
  provider:
    description: 'Cloud Provider'
    required: true
  tailcall-config:
    description: 'Tailcall configuration file'
    required: true
  tailcall-version:
    description: 'Tailcall version'
    required: false
    default: 'latest'
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: false
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: false
  aws-region:
    description: 'AWS Region'
    required: false
  aws-iam-role:
    description: 'AWS IAM Role'
    required: false
    default: 'iam_for_tailcall'
  aws-lambda-function-name:
    description: 'AWS Lambda Function Name'
    required: false
    default: 'tailcall'
  terraform-api-token:
    description: 'Terraform API token'
    required: false
  terraform-org:
    description: 'Terraform Organization'
    required: false
  terraform-workspace:
    description: 'Terraform Workspace'
    required: false
  fly-api-token:
    description: 'Fly.io API token'
    required: false
  fly-app-name:
    description: 'Fly.io App Name'
    required: false
    default: "${{ github.repository_owner }}_${{ github.repository }}"
  fly-region:
    description: 'Fly.io Region'
    required: false
    default: 'ord'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PROVIDER: ${{ inputs.provider }}
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    AWS_REGION: ${{ inputs.aws-region }}
    AWS_IAM_ROLE: ${{ inputs.aws-iam-role }}
    AWS_LAMBDA_FUNCTION_NAME: ${{ inputs.aws-lambda-function-name }}
    TERRAFORM_API_TOKEN: ${{ inputs.terraform-api-token }}
    TERRAFORM_ORG: ${{ inputs.terraform-org }}
    TERRAFORM_WORKSPACE: ${{ inputs.terraform-workspace }}
    FLY_API_TOKEN: ${{ inputs.fly-api-token }}
    FLY_APP_NAME: ${{ inputs.fly-app-name }}
    FLY_REGION: ${{ inputs.fly-region }}
    TAILCALL_VERSION: ${{ inputs.tailcall-version }}
    TAILCALL_CONFIG: ${{ inputs.tailcall-config }}