# action.yml
name: 'Deploy tailcall'
description: 'Deploy tailcall from a config'
inputs:
  aws-access-key-id:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws-secret-access-key:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
  aws-region:
    description: 'AWS_REGION'
    required: true
  aws-iam-role:
    description: 'AWS_IAM_ROLE'
    default: 'iam_for_tailcall'
    required: false
  aws-lambda-function-name:
    description: 'AWS_LAMBDA_FUNCTION_NAME'
    default: 'tailcall'
    required: false
  config:
    description: 'Tailcall config path'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    AWS_REGION: ${{ inputs.aws-region }}
    AWS_IAM_ROLE: ${{ inputs.aws-iam-role }}
    AWS_LAMBDA_FUNCTION_NAME: ${{ inputs.aws-lambda-function-name }}
    CONFIG: ${{ inputs.config }}
