# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  aws-access-key-id:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws-secret-access-key:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
  config:
    description: 'Tailcall config path'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.secret-access-key }}
    - ${{ inputs.config }}
