name: 'Tailcall Deploy Action'
description: 'Deploy Tailcall application with AWS and Fly.io configurations'
inputs:
  aws:
    type: object
    required: false
    properties:
      access-key-id:
        description: 'AWS Access Key ID'
        required: true
        type: string
      secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      region:
        description: 'AWS Region'
        required: true
        type: string
      iam-role:
        description: 'AWS IAM Role'
        required: false
        type: string
        default: 'iam_for_tailcall'
      lambda-function-name:
        description: 'AWS Lambda Function Name'
        required: false
        type: string
        default: 'tailcall'
  fly:
    type: object
    required: false
    properties:
      api-key:
        description: 'Fly.io API Key'
        required: true
        type: string
  tailcall-config:
    description: 'Tailcall configuration file'
    required: true
    type: string
runs:
  using: 'node12'
  main: 'index.js'