on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Deploy Tailcall
    steps:
      - name: Deploy Tailcall
        id: deploy-tailcall
        uses: tailcallhq/gh-action@22297e64fc4164321ec69c4bee82c6b468b50bbf
        with:
          aws-access-key-id: 'aws-access-key-id'
          aws-secret-access-key: 'aws-secret-access-key'
          aws-region: 'us-east-1'
          config: 'config/config.graphql'