on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: tailcallhq/gh-action@7364770111a7d510f4502b9fe902ff38fbb9dd1c
        with:
          aws-access-key-id: 'aws-access-key-id'
          aws-secret-access-key: 'aws-secret-access-key'
          config: './tailcall.graphql'