on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Deploy Tailcall
    steps:
      - name: Deploy Tailcall
        id: deploy-tailcall
        uses: tailcallhq/gh-action@6ca6da0c3bfd3d58a627214f8a8d4eaa5e8c0508
        with:
          aws-access-key-id: 'aws-access-key-id'
          aws-secret-access-key: 'aws-secret-access-key'
          aws-region: 'us-east-1'
          config: 'config/config.graphql'